
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "BYMRJFnGHJQjeLlfSy+KKJOXXjPRFU208vhO6dKOs2lxQZn+wae+amsZzY/rmUJm8+6NrgUI0Upr2hv5IItSJeODyHCYQMZNp+ToQ9HMaTpT8mpE/UgFcnpnOUFZxrfHsRH/O/mwnivcfSfc/6dE/fOtEuzFrWlL4HRXuY7lYqAdT5U2kk7qbkVmJBi7rmRQXQA4Hv7zb9+kYxOJ6eANzYsIJKY73nv/OxnrwaU5UtiGQjr/6taI5vxLWf0JXtsfmPRbm5XCa+899e4OJYbhCDAajBxXbD5ZotjKhLC5MR6vO+YyRTG4B7y09P+kldyAoT2YllkoOo93W5tn/t8jJJBFaZ4/ZVQxuZChmkmKO9+q02b2JZeOg+5QrIdft5ou6V2FxqlnBiTnvywnZZPr87a0iKGPPHKJMQ7RLrPJSaPvPj6nHudlV4j5soquXHL+dH3ZyojZxTkSaakI7s8dx53Z+wm8W7KBJVituj+ZV3rpfvYbQFxfWjhx5e8k9ngHUQDx9fpkVGJ3G4/UF8nDV+6ZrISLGHxN/lauJ7HAUI2mNR5KM4WCeDlMfTbPwb5LAkX7kRA/ZeB0+SXb4n2Da4Y4xSnlHevyOespHo1BANnZHv3uIoYTK1Khw85OTA/8N1plk6Q3O5GMEUjcgl6aMsf9JdK9fCg3CCvt22qt5Kc="


install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-3.7.3-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client

      
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
