
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ECx04QvkVy7vU0l9SRLeJZHJ9oVFxG5gttiGGHUAnvHx+nKP3DZ0VFG+/wqF7fNXLAPM5aoMQTglkO19/Q7lOvGPqzoim4uKvHjjtVkwLIcje78ud6UIY1NEPNDLrakClXVuSngt0VMkQxVo/gEYBTiuE7ljpNnoDzAttpo8Zsx4ThhSsT+bcg12xazg8qryDv+FfpAVMdsJ4kWoXi0D/ihKtgkYpiOO9J2J5seNdzqANsnaNZEIFLeDuGy8A7WLq33c5lRDWXL/ZfZekMzlkCqMd5P64UAqkvFJJR9pdDm9rqCLcDo4zRVPNVOExg1YSvvvRy3vzJYgy5DjmmRpaszV/fqD5v0WecF1EVkKbjjWPV2W3ijjnsQ2BsqjCl1watdZOt4VZG6g8redXUUaLEucy2Q+M7+zH6UDKQqzVEnfkyvH9zba9O9L2tEioVxUOW1qBzFEgX/aN45Ztb4PVC8MLwQvtqA5cF3OJ24HSX1gj0Xs07KP3tU931iwGoGoNkew/o35sOKl6F8MrG+gYdZKMS81/mpv6V8BZfzqMXTA6uinTrMoTblOhqoM6FKnGpHx5hJKLRTverfUifwGibbuwaTCXVhX4qnbaBeyT27LtPQ4wbphBbpjZCwpVwpS2/gs/1mGzTQgFZRff8+HnNtSfBc9SDb3zTDz9hAce10="


install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-3.7.3-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client

      
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
