travis:
  secure:
    BINSTAR_TOKEN: pGu8c66rPJiyHaBW5q7df6yfDADBoatZ97FYlXr415k9Ilc996m+l7GZ3Sw+V5VnDnRXg7YQ9Yq19hEmjjFJUryligDE9SOAAvzibeqvzKarLpZikQLk4b4qGnKZFlJ990bCsm7zYiaMNRtCzUe8JjR1awcbganZJmbsVhgm63v6DKbkVL6RQflYdqi8H2w2qWr3XyNuP4Z+pZBN3AaKwzuyhvSVeVfGM0YFCzQSggbFJwRCxfckiRJIsaaQtsRHJqCMJ/JXzFu+msG0isu7cyM8H88iv4zMlSetkEm5VHe4Wi+kBiX+jP1PT7SWnAgXrXcKSWPJIx+u0ESFbjGlgZ2pvGWpwsgG2RtFgv/7MSBtvHJ+YR2oxKkg/rrpFn44x3BM08fdmdQLp5SQcEAgHw7nb8sAGx+tBIpSHottKkdYDCxOum9nQo8bV8EVsrR3MdlacqCMvbuO4zOlNhLSVA7s2lagxehw++XpTObXtaLoMLS0AxqRsE28XM7/YP4/bHkUgac9Q4eI06UOTg5gVoXLVWYOWlOJWmzo5/6y/5pwy4W80JA+YwOkyPZy07Mk+ExiFgnHyhc1OLnbXssAD7IPvAHpw9UsOeJhvBIbyiMVumFcaDbIxM6wERxxCvDUFt2C3Yg7Z7WrHAr0mqL7PQAv5r5QDnR4UpxFsoMvzAA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
