travis:
  secure:
    BINSTAR_TOKEN: BYMRJFnGHJQjeLlfSy+KKJOXXjPRFU208vhO6dKOs2lxQZn+wae+amsZzY/rmUJm8+6NrgUI0Upr2hv5IItSJeODyHCYQMZNp+ToQ9HMaTpT8mpE/UgFcnpnOUFZxrfHsRH/O/mwnivcfSfc/6dE/fOtEuzFrWlL4HRXuY7lYqAdT5U2kk7qbkVmJBi7rmRQXQA4Hv7zb9+kYxOJ6eANzYsIJKY73nv/OxnrwaU5UtiGQjr/6taI5vxLWf0JXtsfmPRbm5XCa+899e4OJYbhCDAajBxXbD5ZotjKhLC5MR6vO+YyRTG4B7y09P+kldyAoT2YllkoOo93W5tn/t8jJJBFaZ4/ZVQxuZChmkmKO9+q02b2JZeOg+5QrIdft5ou6V2FxqlnBiTnvywnZZPr87a0iKGPPHKJMQ7RLrPJSaPvPj6nHudlV4j5soquXHL+dH3ZyojZxTkSaakI7s8dx53Z+wm8W7KBJVituj+ZV3rpfvYbQFxfWjhx5e8k9ngHUQDx9fpkVGJ3G4/UF8nDV+6ZrISLGHxN/lauJ7HAUI2mNR5KM4WCeDlMfTbPwb5LAkX7kRA/ZeB0+SXb4n2Da4Y4xSnlHevyOespHo1BANnZHv3uIoYTK1Khw85OTA/8N1plk6Q3O5GMEUjcgl6aMsf9JdK9fCg3CCvt22qt5Kc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
